[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["cargo"] }
colored = "2.0.0"
itertools = "0.10.5"
paste = "1.0.9"
pathfinding = "4.0.0"

[profile.release]
debug = true
